### ISSUE TITLE
Mention docopt

### ISSUE THREAD

**Issue by gramster** [tukkek/notablepython#2]
argparse is something of an abomination. If you're going to mention it, mention docopt too.

**Comment by tukkek** [comment]
Thanks, I've never had to create anything more than very simple argument inputs, which I just parse myself. I have added a link to docopt, let me know if it's OK since I haven't used it myself https://github.com/tukkek/notablepython/blob/master/README.md#honorable-mentions

**Comment by gramster** [comment]
Docopt is awesome. It’s not really a “Pythonic DSL” though - you just give
the command line help string and it generates the parser to match that.


On September 12, 2017 at 3:37:44 PM, tukkek (notifications@github.com)
wrote:

Thanks, I've never had to create anything more than very simple argument
input, which just parse myself. I have added a link to docopt, let me know
if it's OK since I haven't used it myself
https://github.com/tukkek/notablepython/blob/master/README.md#honorable-mentions

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tukkek/notablepython/issues/2#issuecomment-329003931>,
or mute the thread

**Comment by tukkek** [comment]
The fact it's pythonic is [their own words](https://github.com/docopt/docopt). I also don't see how it isn't a DSL when it proclaims to be a new language and it's very domain-specific (["Command-line interface description language"](http://docopt.org/))?

**Comment by gramster** [comment]
It’s Pythonic, and it uses a DSL, but it’s not a Pythonic DSL :-)


On September 12, 2017 at 8:45:50 PM, tukkek (notifications@github.com)
wrote:

The fact it's pythonic is their own words <https://github.com/docopt/docopt>.
I also don't see how it isn't a DSL when it proclaims to be a new language
and it's very domain-specific ("Command-line interface description language"
<http://docopt.org/>)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tukkek/notablepython/issues/2#issuecomment-329050858>,
or mute the thread

**Comment by tukkek** [comment]
Point taken - that was not the meaning I intended, after all! I've rewritten it to:

> docopt is a pythonic third-party library that offers a DSL for describing your command-line input and options.
