### ISSUE TITLE
Print Formatting

### ISSUE THREAD

**Issue by artieleach** [tukkek/notablepython#3]
the standard for [aligning output](https://www.python.org/dev/peps/pep-3101/) in version 3 is `print("{:>_10}".format(hello))` rather than the listed `print(hello.rjust(20))`

**Comment by tukkek** [comment]
I personally find that a bit hard to read but I'll add it to the relevant section anyways! Thank you!

**Comment by tukkek** [comment]
Added through 518609cf032a3d8378aa15289a2f50df3f0022be.
